export const types = {
    SEND_REQUEST : 'SEND_REQUEST',
    SEND_REQUEST_SUCESS :'SEND_REQUEST_SUCESS',
    SEND_REQUEST_FAILURE : 'SEND_REQUEST_FAILURE',
    LOAD_MORE_DETAILS : 'LOAD_MORE_DETAILS',
    LOAD_MORE_DETAILS_SUCCESS : 'LOAD_MORE_DETAILS_SUCCESS',
    LOAD_MORE_DETAILS_ERROR : 'LOAD_MORE_DETAILS_ERROR',
}
export const PASSANGER_START_PAGE = 0;
export const PASSANGER_DEFAULT_SIZE = 40;
export const FETCH_PAGE = 1;

